<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BiGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiGroupRepository extends EntityRepository
{
	# Do Something Great Here
}