<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BiUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BiUserRepository extends EntityRepository
{

	# Do Something Great Here
}
